### ISSUE TITLE
Accessories not found when Homebridge is being rebooted together with NodeRED

### ISSUE THREAD

**Issue by iRonin** [NorthernMan54/node-red-contrib-homebridge-automation#6]
When both Homebridge and NodeRED are restarted and NodeRED starts too early it can't find the accessories until it is restarted again. 

Perhaps it could be retrying discovery after some time?

**Comment by NorthernMan54** [comment]
In my setup I'm using systemd to start all my services, and am not starting node-red until after homebridge is started

https://stackoverflow.com/questions/49643551/systemd-service-b-to-start-after-another-service-a-only-if-service-a-exists

But you are raising a very good point, as the service should on a regular basis rediscover devices.  Let me look into this.

**Comment by iRonin** [comment]
I'm running both via Docker on my Synology DSM and they all have simple auto-restart selected.

**Comment by NorthernMan54** [comment]
I have been running thru a couple of scenarios, and device discovery happens every 15 minutes, so if you add or change a homebridge instance it will be discovered.  But I also discovered is that 'hb-event' goes dumb if node-red is started before homebridge is ready.  It tries to register for device events from homebridge only once, and never tries again.  Is this the behaviour you are seeing?

**Comment by NorthernMan54** [comment]
Try version 0.0.43, I fixed the problem I found above.  It was a surprisingly simple fix.

**Comment by iRonin** [comment]
Great! I'm waiting for the version to show up in Node RED so I can upgrade there; it still shows 0.0.42.

I encountered the issue when I tried to debug why suddenly HB events were not triggered in NRED. I didn't find explanation but the restart helped.  Hopefully the new version will fix this too 👍🏻

**Comment by NorthernMan54** [comment]
My test case was start node-red then start homebridge about a minute later.  And ensure that events are registered.

Am thinking there is another test case for restarting homebridge and ensuring events reregister.  Let me check out that one tonight.

**Comment by iRonin** [comment]
I forgot I have to update it via CLI, done this now.

**Comment by b2un0** [comment]
@NorthernMan54 can you please publish this Flow under http://flows.nodered.org so we can install and update this native in NodeRED? Its hard to update if you run NodeRED as Docker Container with Docker Volumes.

**Comment by NorthernMan54** [comment]
Big question, is it ready for prime time yet?

I’m going to change the name to homebridge-automation as that defines it really well, but are there any other issues that need resolving first?

One that is in the back of my mind is the hb-event node, and the need to merge messages from controlling an rgb light.  As each characteristic is an individual message it makes the flows challenging.  In my flows I have taken to adding a node merge messages.

**Comment by b2un0** [comment]
i think so, the Plugin works really nice (just tested some basic rules).

Whit this plugin i can do the following:
- replace all my differenz zigbee Hubs with `deconz`  and combine all zigbee devices to one big network and discover all devices with `homebridge-hue`.

But the biggest **win** of this Node-Red Plugin is: i can finally simulate the Philips Hue Motion Detector Lab Skill for every motion detector (not only Hue!):
- turn the light only on if the light was off
- then turn the light after X Minutes off
- reset the timer on every motion detection (this is the biggest deal!)


So i think some other people would do the same and the biggest goal i think is: your Node-Red flow becomes more user > more tester > more contributors?

the suggested name is great! let us know when you renamed and published the flow!

**Comment by fschaefer** [comment]
FYI: I've a similar issue. My Homebridge is started with a 30 seconds delay after Node-RED, because Node-RED provides some pseudo HomeKit accessories to Homebridge. After a reboot the hb-control nodes device field and the list are empty. A refresh doesn't recover the devices. A restart of Node-RED 
resolves the issue. So on boot I have to start Node-RED, start Homebridge and restart Node-Red to habe a working setup. 

Regarding the name change, `node-red-contrib-homebridge-automation` would be appropriate.

**Comment by NorthernMan54** [comment]
@fschaefer Can you explain your setup further and why your starting homebridge after node-red?  In my setup I start node-red last ( After the same 30 seconds ). 

If you are starting before all your homebridge instances are running, it will run discover again every 15 minutes. And should repopulate everything

For my pseudo HomeKit accessories, I'm using the homekit-bridged node-red node.

**Comment by NorthernMan54** [comment]
Name was changed....

**Comment by fschaefer** [comment]
I just refactored my setup and I guess I can switch the process and delay the Node-RED now, like you do.

Why is the discovery time 15 minutes? Isn't the discovery just a HTTP-request to the bridges in the local network? Some services penetrate the bridge every 5 seconds, so maybe we can reduce the rediscovery time a lot. I also noticed the retry count of 1000. Is this to stop the discovery after some time? Maybe rediscovery can be just throttled. Instead giving up after 1000 tries, double the time to the next discovery and reset after some event.

Regarding the name change: you could clone the project, reset it to the old name and update the readme to link to the new repository. So all those links out there can find the new repository. Maybe it's time to publish this on npm?

**Comment by NorthernMan54** [comment]
That retries is for event registration, and not discovery

The discovery process is very complex and not just a simple http request, as the node then parses and builds a model of all you devices in memory, and shares it Internally etc.

The 15 minutes has been pretty constant with this node and my homebridge-Alexa, and it really hasn’t been an issue.  I think a tip for starting last is all that’s needed to avoid the issue, and I will add this to the install instructions.

Before I publish I’m going to make one final change to event messages and put them into a single message. So that events with changes to multiple characteristics like a color light change get emitted as a single message.  But no change to events with a single characteristic change.

**Comment by fschaefer** [comment]
Thank you for clarifying. I'll report back if my issue is resolved by delaying the Node-RED startup.

Great stuff you do here. It's really a lot of fun playing with the node-red-contrib-homebridge-automation nodes. Keep it up!

**Comment by NorthernMan54** [comment]
Am closing this is the original issue is resolved

**Comment by fschaefer** [comment]
FYI: my issue is also resolved.
